### ISSUE TITLE
@timeout renamed to @delay or @future?

### ISSUE THREAD

**Issue by StrikeForceZero** [NetanelBasal/helpful-decorators#1]
These look great. Haven't tried them out yet.

But when I first read `@timeout`, my initial intuition made me think of `Promise.timeout()` used in some promise libraries like bluebird. Since `setTimeout` has been around since the beginning of JavaScript, I'm not sure if it's appropriate to use `@delay` or `@future`. At least it would hint for something to execute in the future, or after a delay.

Just throwing this out there for consideration. Maybe I'm the odd one out.

Not intending to turn this "issue" into a feature request but it could be really cool to see some decorators that worked with async functions as well just like Bluebird's timeout/delay.

**Comment by NetanelBasal** [comment]
Thanks for your feedback. Let's leave it open and see if there are more like you :).

**Comment by cgmx** [comment]
I agree with @StrikeForceZero, I'd rename `@timeout` to `@delay`. Seeing `@timeout` makes me think of `Promise.timeout()`.

**Comment by bengry** [comment]
+1

**Comment by NetanelBasal** [comment]
Changed to @delay in 1.5.0, thanks, guys.
