### ISSUE TITLE
Template literals in IE

### ISSUE THREAD

**Issue by Binek115** [NetanelBasal/helpful-decorators#10]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Application with helpful-decorators will not open on IE because browser does not support template literals which is used in measure function inside console.log().

## Expected behavior
Application will open correctly.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-b7lgd7

## Environment
helpful-decorators version: 2.0.5

Browser:
- [X] IE version 11

**Comment by NetanelBasal** [comment]
Why are you not compiling the code with Typescript or Babel?

**Comment by NetanelBasal** [comment]
Decorators don't work natively in the browser.

**Comment by Binek115** [comment]
I have updated reproduction link
