### ISSUE TITLE
@measure for async functions

### ISSUE THREAD

**Issue by singhabhilash** [NetanelBasal/helpful-decorators#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

@measure only works for synchronous functions at the moment. Will be a nice addition to make it work for async functions as well.

## Expected behavior

@measure should work for both sync and async functions.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR

**Comment by ruowan** [comment]
I would like to add an async function.

**Comment by ruowan** [comment]
https://github.com/NetanelBasal/helpful-decorators/pull/23
