### ISSUE TITLE
Bind decorator expects 3 parameters

### ISSUE THREAD

**Issue by hakimio** [NetanelBasal/helpful-decorators#21]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Trying to use `@bind` decorator without any arguments results in "Expected 3 arguments but got 0" TypeScript error.

## Expected behavior
`@bind()` decorator should work without any arguments.

## Minimal reproduction of the problem with instructions
Try to use `@bind()` decorator in Angular 9 project.

## Environment

<pre><code>
helpful-decorators version: 2.0.6

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: 12
- Platform:  Windows

Others:
TypeScript: 3.8.3

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR. Thanks.

**Comment by hakimio** [comment]
I think the only thing you have to do to fix this is wrap it in another function:
```ts
export function bind() {
    return function (target: any, key: string, descriptor: PropertyDescriptor): PropertyDescriptor {
        // ...
    }
}
```

**Comment by NetanelBasal** [comment]
https://www.typescriptlang.org/v2/en/play?#code/GYVwdgxgLglg9mABAIxmAJgCigQwE4DmAplAFyI5gCeANIgNZFXmW2LpEDOEeMADlDh4W1AJQiqiAN4BYAFCJEAGxKJgSALzsuPfoLwA6AG44lIIgG558xTGCJsVPkTj31iAIQatAclCRYBB9RaRtFRCgACzw4AHdEMCJ4gFE8GLxMAAMAARwQQVQMbQghHH1ECEpEBCVJZCIKPj4lGCJ0CLhEAFsSSLh0TgS4MkQAEikoJxc3MABfTNErBURZ62WAenXEAEkkbeSARgOK0xawAkQAeWQAKyJoAw5gNCIABRjnPEnESJxBnEQnBgHAAtERgMB7lBqvYiCYzGU0BcokQwptEMQoFAiHg1EIIpEGnwPjjvrFIjAIJFEDBBvUkYg8ERmjgIG0DIgACoUwaVECcLg0sDPMAwbForZMiAgPBAhAUIpVABEl3yMMBuAg9EBfFZRCViBx6QMYRU0KeaCR7zgn2+WmApgFSzCTKgMqQsmWihKwpgBBlOGQKnIUDw5hoYUUmMwIU94XCdgcFtF52ttskAB8MwTaYhvFpcIQSAZicNhlNEFmc5wDL9OJdYmA06SqJhGFQQlXJs5XGokF5fP5oPAwMFQl744ySO6+0tJys1vOzSg4OB0AAxTR9gyFLBRWmLSPhZNWklfSQFsOWI+Ka53B7Jt5nybYHl0dt0OPzioIZ7+vCBsGERXhGE7xtGsY3pOrozsgq4YJuc7frMoHfoCJCYPC5iQWBk7uFoWHXrh8YcGaDT7pwADa7YALpIfOqy4bMh64SeqbPheaiOkR84wXgSBwWuiFHihR4ClAmGmOYEg4fO+GIIR9ELsssxLIx8gQEofyDAAgk0ADCcBdHwCBEGA0Jfj6nChiA0BCDG44kXA0o9OZO79FQBg4Og6DJEYZlQAAMrS2KJBkPiaZS9A+HQFEGAg+ktFqLGKOpyzZLuYQJUl9CYKMcIBTJjnhFZcAqAYShwAQeUFeZKXKbMQA

**Comment by hakimio** [comment]
Ok, sorry, it works without paranthesis.
