### ISSUE TITLE
[FR] refactor to only import needed decorators-> lodash modules

### ISSUE THREAD

**Issue by farfromrefug** [NetanelBasal/helpful-decorators#6]
I am using your module using webpack and i only want throttle.
But right now the way it is written , it will import all in my webpack build plus all lodash deps.
I think i can solve this by importing ```helpful-decorators/dist-src/throttle``` but then i get no typings.
Could you make it so that we can import ```helpful-decorators/throttle``` ?

That would be awesome!

Thanks

**Comment by NetanelBasal** [comment]
It's not. I only import the throttle module: 

`const throttleFn = require('lodash.throttle');`

**Comment by farfromrefug** [comment]
@NetanelBasal yes you do but in ```index.ts``` your [import](https://github.com/NetanelBasal/helpful-decorators/blob/master/src/index.ts) all decorators.
Each one importing its lodash counterpart.

So you always end up with up even if you only use one

**Comment by NetanelBasal** [comment]
No, Webpack should tree shake the rest.

**Comment by farfromrefug** [comment]
What do you mean? and it doesn't. I have tested it using webpack report feature

**Comment by NetanelBasal** [comment]
You should build in production mode, and Webpack should tree shake what's not in use.

**Comment by farfromrefug** [comment]
@NetanelBasal thanks for letting me know about tree shaking. I didn't know about it.
Spent a few days making my app work with tree shaking. Now it does. however even if webpack sees that only throttle is used in my project:
```
[185] ../node_modules/helpful-decorators/dist-web/index.js 4.13 KiB {2} [built]
      [only some exports used: throttle]
```
the other lodash imports are not removed. Could it be because those are not ECMAScript modules?
```
[248] ../node_modules/lodash.debounce/index.js 10.5 KiB {2} [built]
      ModuleConcatenation bailout: Module is not an ECMAScript module
[249] ../node_modules/lodash.throttle/index.js 13 KiB {2} [built]
      ModuleConcatenation bailout: Module is not an ECMAScript module
[250] ../node_modules/lodash.once/index.js 6.93 KiB {2} [built]
      ModuleConcatenation bailout: Module is not an ECMAScript module
[251] ../node_modules/lodash.memoize/index.js 16.6 KiB {2} [built]
      ModuleConcatenation bailout: Module is not an ECMAScript modul
```

**Comment by NetanelBasal** [comment]
Weird, because the file itself is. Maybe we should add the `sideEffects: false` option.

**Comment by farfromrefug** [comment]
@NetanelBasal what do you mean add it as an option? ```"sideEffects": false``` is already in the package.json file of your module

**Comment by NetanelBasal** [comment]
Here. https://github.com/NetanelBasal/helpful-decorators/blob/master/package.json

**Comment by farfromrefug** [comment]
@NetanelBasal it is already there in the  published  package
<img width="631" alt="Screen Shot 2019-04-10 at 17 48 47" src="https://user-images.githubusercontent.com/655344/55893608-eb38f780-5bb8-11e9-8e1f-1045f07e54cc.png">

**Comment by NetanelBasal** [comment]
Oh missed that.
