### ISSUE TITLE
Decorated method returns nothing

### ISSUE THREAD

**Issue by Ledzz** [NetanelBasal/helpful-decorators#8]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Method decorated with `@measure` returns nothing. Haven't tested with other decorators.

## Expected behavior

Returned value does not change

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/typescript-okyls9

</code></pre>

**Comment by NetanelBasal** [comment]
The issue is here:

```ts
  descriptor.value = function(...args) {
    const start = performance.now();
    originalMethod.apply(this, args);
    const end = performance.now();
    console.log(`Call to ${propertyKey} took ${(end - start).toFixed(2)} milliseconds.`);
  };
```

It should be:

```ts
  descriptor.value = function(...args) {
    const start = performance.now();
    const result = originalMethod.apply(this, args);
    const end = performance.now();
    console.log(`Call to ${propertyKey} took ${(end - start).toFixed(2)} milliseconds.`);
    return result;
  };
```

Do you want to create a PR?

**Comment by Ledzz** [comment]
yes, I'll do it today :)
